// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file PsuData.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

#ifndef FAST_DDS_GENERATED__MVI_PSUDATA_HPP
#define FAST_DDS_GENERATED__MVI_PSUDATA_HPP

#include <cstdint>
#include <utility>
#include <vector>


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(PSUDATA_SOURCE)
#define PSUDATA_DllAPI __declspec( dllexport )
#else
#define PSUDATA_DllAPI __declspec( dllimport )
#endif // PSUDATA_SOURCE
#else
#define PSUDATA_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define PSUDATA_DllAPI
#endif // _WIN32

namespace MVI {

/*!
 * @brief This class represents the structure PsuData defined by the user in the IDL file.
 * @ingroup PsuData
 */
class PsuData
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport PsuData()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~PsuData()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object PsuData that will be copied.
     */
    eProsima_user_DllExport PsuData(
            const PsuData& x)
    {
                    m_timeStamp = x.m_timeStamp;

                    m_setpoint = x.m_setpoint;

                    m_iMeasured = x.m_iMeasured;

                    m_uMeasured = x.m_uMeasured;

                    m_flags = x.m_flags;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object PsuData that will be copied.
     */
    eProsima_user_DllExport PsuData(
            PsuData&& x) noexcept
    {
        m_timeStamp = x.m_timeStamp;
        m_setpoint = x.m_setpoint;
        m_iMeasured = x.m_iMeasured;
        m_uMeasured = x.m_uMeasured;
        m_flags = x.m_flags;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object PsuData that will be copied.
     */
    eProsima_user_DllExport PsuData& operator =(
            const PsuData& x)
    {

                    m_timeStamp = x.m_timeStamp;

                    m_setpoint = x.m_setpoint;

                    m_iMeasured = x.m_iMeasured;

                    m_uMeasured = x.m_uMeasured;

                    m_flags = x.m_flags;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object PsuData that will be copied.
     */
    eProsima_user_DllExport PsuData& operator =(
            PsuData&& x) noexcept
    {

        m_timeStamp = x.m_timeStamp;
        m_setpoint = x.m_setpoint;
        m_iMeasured = x.m_iMeasured;
        m_uMeasured = x.m_uMeasured;
        m_flags = x.m_flags;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x PsuData object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const PsuData& x) const
    {
        return (m_timeStamp == x.m_timeStamp &&
           m_setpoint == x.m_setpoint &&
           m_iMeasured == x.m_iMeasured &&
           m_uMeasured == x.m_uMeasured &&
           m_flags == x.m_flags);
    }

    /*!
     * @brief Comparison operator.
     * @param x PsuData object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const PsuData& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member timeStamp
     * @param _timeStamp New value for member timeStamp
     */
    eProsima_user_DllExport void timeStamp(
            uint32_t _timeStamp)
    {
        m_timeStamp = _timeStamp;
    }

    /*!
     * @brief This function returns the value of member timeStamp
     * @return Value of member timeStamp
     */
    eProsima_user_DllExport uint32_t timeStamp() const
    {
        return m_timeStamp;
    }

    /*!
     * @brief This function returns a reference to member timeStamp
     * @return Reference to member timeStamp
     */
    eProsima_user_DllExport uint32_t& timeStamp()
    {
        return m_timeStamp;
    }


    /*!
     * @brief This function sets a value in member setpoint
     * @param _setpoint New value for member setpoint
     */
    eProsima_user_DllExport void setpoint(
            double _setpoint)
    {
        m_setpoint = _setpoint;
    }

    /*!
     * @brief This function returns the value of member setpoint
     * @return Value of member setpoint
     */
    eProsima_user_DllExport double setpoint() const
    {
        return m_setpoint;
    }

    /*!
     * @brief This function returns a reference to member setpoint
     * @return Reference to member setpoint
     */
    eProsima_user_DllExport double& setpoint()
    {
        return m_setpoint;
    }


    /*!
     * @brief This function sets a value in member iMeasured
     * @param _iMeasured New value for member iMeasured
     */
    eProsima_user_DllExport void iMeasured(
            double _iMeasured)
    {
        m_iMeasured = _iMeasured;
    }

    /*!
     * @brief This function returns the value of member iMeasured
     * @return Value of member iMeasured
     */
    eProsima_user_DllExport double iMeasured() const
    {
        return m_iMeasured;
    }

    /*!
     * @brief This function returns a reference to member iMeasured
     * @return Reference to member iMeasured
     */
    eProsima_user_DllExport double& iMeasured()
    {
        return m_iMeasured;
    }


    /*!
     * @brief This function sets a value in member uMeasured
     * @param _uMeasured New value for member uMeasured
     */
    eProsima_user_DllExport void uMeasured(
            double _uMeasured)
    {
        m_uMeasured = _uMeasured;
    }

    /*!
     * @brief This function returns the value of member uMeasured
     * @return Value of member uMeasured
     */
    eProsima_user_DllExport double uMeasured() const
    {
        return m_uMeasured;
    }

    /*!
     * @brief This function returns a reference to member uMeasured
     * @return Reference to member uMeasured
     */
    eProsima_user_DllExport double& uMeasured()
    {
        return m_uMeasured;
    }


    /*!
     * @brief This function sets a value in member flags
     * @param _flags New value for member flags
     */
    eProsima_user_DllExport void flags(
            uint16_t _flags)
    {
        m_flags = _flags;
    }

    /*!
     * @brief This function returns the value of member flags
     * @return Value of member flags
     */
    eProsima_user_DllExport uint16_t flags() const
    {
        return m_flags;
    }

    /*!
     * @brief This function returns a reference to member flags
     * @return Reference to member flags
     */
    eProsima_user_DllExport uint16_t& flags()
    {
        return m_flags;
    }



private:

    uint32_t m_timeStamp{0};
    double m_setpoint{0.0};
    double m_iMeasured{0.0};
    double m_uMeasured{0.0};
    uint16_t m_flags{0};

};
/*!
 * @brief This class represents the structure PsuDataSeq defined by the user in the IDL file.
 * @ingroup PsuData
 */
class PsuDataSeq
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport PsuDataSeq()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~PsuDataSeq()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object PsuDataSeq that will be copied.
     */
    eProsima_user_DllExport PsuDataSeq(
            const PsuDataSeq& x)
    {
                    m_data = x.m_data;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object PsuDataSeq that will be copied.
     */
    eProsima_user_DllExport PsuDataSeq(
            PsuDataSeq&& x) noexcept
    {
        m_data = std::move(x.m_data);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object PsuDataSeq that will be copied.
     */
    eProsima_user_DllExport PsuDataSeq& operator =(
            const PsuDataSeq& x)
    {

                    m_data = x.m_data;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object PsuDataSeq that will be copied.
     */
    eProsima_user_DllExport PsuDataSeq& operator =(
            PsuDataSeq&& x) noexcept
    {

        m_data = std::move(x.m_data);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x PsuDataSeq object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const PsuDataSeq& x) const
    {
        return (m_data == x.m_data);
    }

    /*!
     * @brief Comparison operator.
     * @param x PsuDataSeq object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const PsuDataSeq& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member data
     * @param _data New value to be copied in member data
     */
    eProsima_user_DllExport void data(
            const std::vector<PsuData>& _data)
    {
        m_data = _data;
    }

    /*!
     * @brief This function moves the value in member data
     * @param _data New value to be moved in member data
     */
    eProsima_user_DllExport void data(
            std::vector<PsuData>&& _data)
    {
        m_data = std::move(_data);
    }

    /*!
     * @brief This function returns a constant reference to member data
     * @return Constant reference to member data
     */
    eProsima_user_DllExport const std::vector<PsuData>& data() const
    {
        return m_data;
    }

    /*!
     * @brief This function returns a reference to member data
     * @return Reference to member data
     */
    eProsima_user_DllExport std::vector<PsuData>& data()
    {
        return m_data;
    }



private:

    std::vector<PsuData> m_data;

};

} // namespace MVI

#endif // _FAST_DDS_GENERATED_MVI_PSUDATA_HPP_


