// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file PsuDataTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

#include "PsuDataTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "PsuData.hpp"


using namespace eprosima::fastdds::dds::xtypes;

namespace MVI {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_PsuData_type_identifier(
        TypeIdentifierPair& type_ids_PsuData)
{

    ReturnCode_t return_code_PsuData {eprosima::fastdds::dds::RETCODE_OK};
    return_code_PsuData =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "MVI::PsuData", type_ids_PsuData);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_PsuData)
    {
        StructTypeFlag struct_flags_PsuData = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_PsuData = "MVI::PsuData";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_PsuData;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_PsuData;
        CompleteTypeDetail detail_PsuData = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_PsuData, ann_custom_PsuData, type_name_PsuData.to_string());
        CompleteStructHeader header_PsuData;
        header_PsuData = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_PsuData);
        CompleteStructMemberSeq member_seq_PsuData;
        {
            TypeIdentifierPair type_ids_timeStamp;
            ReturnCode_t return_code_timeStamp {eprosima::fastdds::dds::RETCODE_OK};
            return_code_timeStamp =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_timeStamp);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_timeStamp)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "timeStamp Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_timeStamp = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_timeStamp = 0x00000000;
            bool common_timeStamp_ec {false};
            CommonStructMember common_timeStamp {TypeObjectUtils::build_common_struct_member(member_id_timeStamp, member_flags_timeStamp, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_timeStamp, common_timeStamp_ec))};
            if (!common_timeStamp_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure timeStamp member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_timeStamp = "timeStamp";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_timeStamp;
            ann_custom_PsuData.reset();
            CompleteMemberDetail detail_timeStamp = TypeObjectUtils::build_complete_member_detail(name_timeStamp, member_ann_builtin_timeStamp, ann_custom_PsuData);
            CompleteStructMember member_timeStamp = TypeObjectUtils::build_complete_struct_member(common_timeStamp, detail_timeStamp);
            TypeObjectUtils::add_complete_struct_member(member_seq_PsuData, member_timeStamp);
        }
        {
            TypeIdentifierPair type_ids_setpoint;
            ReturnCode_t return_code_setpoint {eprosima::fastdds::dds::RETCODE_OK};
            return_code_setpoint =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_setpoint);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_setpoint)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "setpoint Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_setpoint = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_setpoint = 0x00000001;
            bool common_setpoint_ec {false};
            CommonStructMember common_setpoint {TypeObjectUtils::build_common_struct_member(member_id_setpoint, member_flags_setpoint, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_setpoint, common_setpoint_ec))};
            if (!common_setpoint_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure setpoint member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_setpoint = "setpoint";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_setpoint;
            ann_custom_PsuData.reset();
            CompleteMemberDetail detail_setpoint = TypeObjectUtils::build_complete_member_detail(name_setpoint, member_ann_builtin_setpoint, ann_custom_PsuData);
            CompleteStructMember member_setpoint = TypeObjectUtils::build_complete_struct_member(common_setpoint, detail_setpoint);
            TypeObjectUtils::add_complete_struct_member(member_seq_PsuData, member_setpoint);
        }
        {
            TypeIdentifierPair type_ids_iMeasured;
            ReturnCode_t return_code_iMeasured {eprosima::fastdds::dds::RETCODE_OK};
            return_code_iMeasured =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_iMeasured);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_iMeasured)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "iMeasured Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_iMeasured = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_iMeasured = 0x00000002;
            bool common_iMeasured_ec {false};
            CommonStructMember common_iMeasured {TypeObjectUtils::build_common_struct_member(member_id_iMeasured, member_flags_iMeasured, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_iMeasured, common_iMeasured_ec))};
            if (!common_iMeasured_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure iMeasured member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_iMeasured = "iMeasured";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_iMeasured;
            ann_custom_PsuData.reset();
            CompleteMemberDetail detail_iMeasured = TypeObjectUtils::build_complete_member_detail(name_iMeasured, member_ann_builtin_iMeasured, ann_custom_PsuData);
            CompleteStructMember member_iMeasured = TypeObjectUtils::build_complete_struct_member(common_iMeasured, detail_iMeasured);
            TypeObjectUtils::add_complete_struct_member(member_seq_PsuData, member_iMeasured);
        }
        {
            TypeIdentifierPair type_ids_uMeasured;
            ReturnCode_t return_code_uMeasured {eprosima::fastdds::dds::RETCODE_OK};
            return_code_uMeasured =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_uMeasured);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_uMeasured)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "uMeasured Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_uMeasured = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_uMeasured = 0x00000003;
            bool common_uMeasured_ec {false};
            CommonStructMember common_uMeasured {TypeObjectUtils::build_common_struct_member(member_id_uMeasured, member_flags_uMeasured, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_uMeasured, common_uMeasured_ec))};
            if (!common_uMeasured_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure uMeasured member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_uMeasured = "uMeasured";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_uMeasured;
            ann_custom_PsuData.reset();
            CompleteMemberDetail detail_uMeasured = TypeObjectUtils::build_complete_member_detail(name_uMeasured, member_ann_builtin_uMeasured, ann_custom_PsuData);
            CompleteStructMember member_uMeasured = TypeObjectUtils::build_complete_struct_member(common_uMeasured, detail_uMeasured);
            TypeObjectUtils::add_complete_struct_member(member_seq_PsuData, member_uMeasured);
        }
        {
            TypeIdentifierPair type_ids_flags;
            ReturnCode_t return_code_flags {eprosima::fastdds::dds::RETCODE_OK};
            return_code_flags =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint16_t", type_ids_flags);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_flags)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "flags Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_flags = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_flags = 0x00000004;
            bool common_flags_ec {false};
            CommonStructMember common_flags {TypeObjectUtils::build_common_struct_member(member_id_flags, member_flags_flags, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_flags, common_flags_ec))};
            if (!common_flags_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure flags member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_flags = "flags";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_flags;
            ann_custom_PsuData.reset();
            CompleteMemberDetail detail_flags = TypeObjectUtils::build_complete_member_detail(name_flags, member_ann_builtin_flags, ann_custom_PsuData);
            CompleteStructMember member_flags = TypeObjectUtils::build_complete_struct_member(common_flags, detail_flags);
            TypeObjectUtils::add_complete_struct_member(member_seq_PsuData, member_flags);
        }
        CompleteStructType struct_type_PsuData = TypeObjectUtils::build_complete_struct_type(struct_flags_PsuData, header_PsuData, member_seq_PsuData);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_PsuData, type_name_PsuData.to_string(), type_ids_PsuData))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "MVI::PsuData already registered in TypeObjectRegistry for a different type.");
        }
    }
}// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_PsuDataSeq_type_identifier(
        TypeIdentifierPair& type_ids_PsuDataSeq)
{

    ReturnCode_t return_code_PsuDataSeq {eprosima::fastdds::dds::RETCODE_OK};
    return_code_PsuDataSeq =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "MVI::PsuDataSeq", type_ids_PsuDataSeq);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_PsuDataSeq)
    {
        StructTypeFlag struct_flags_PsuDataSeq = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_PsuDataSeq = "MVI::PsuDataSeq";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_PsuDataSeq;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_PsuDataSeq;
        CompleteTypeDetail detail_PsuDataSeq = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_PsuDataSeq, ann_custom_PsuDataSeq, type_name_PsuDataSeq.to_string());
        CompleteStructHeader header_PsuDataSeq;
        header_PsuDataSeq = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_PsuDataSeq);
        CompleteStructMemberSeq member_seq_PsuDataSeq;
        {
            TypeIdentifierPair type_ids_data;
            ReturnCode_t return_code_data {eprosima::fastdds::dds::RETCODE_OK};
            return_code_data =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_sequence_MVI_PsuData_unbounded", type_ids_data);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_data)
            {
                return_code_data =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "MVI::PsuData", type_ids_data);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_data)
                {
                    ::MVI::register_PsuData_type_identifier(type_ids_data);
                }
                bool element_identifier_anonymous_sequence_MVI_PsuData_unbounded_ec {false};
                TypeIdentifier* element_identifier_anonymous_sequence_MVI_PsuData_unbounded {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_data, element_identifier_anonymous_sequence_MVI_PsuData_unbounded_ec))};
                if (!element_identifier_anonymous_sequence_MVI_PsuData_unbounded_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Sequence element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_sequence_MVI_PsuData_unbounded = EK_COMPLETE;
                if (TK_NONE == type_ids_data.type_identifier2()._d())
                {
                    equiv_kind_anonymous_sequence_MVI_PsuData_unbounded = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_sequence_MVI_PsuData_unbounded = 0;
                PlainCollectionHeader header_anonymous_sequence_MVI_PsuData_unbounded = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_sequence_MVI_PsuData_unbounded, element_flags_anonymous_sequence_MVI_PsuData_unbounded);
                {
                    SBound bound = 0;
                    PlainSequenceSElemDefn seq_sdefn = TypeObjectUtils::build_plain_sequence_s_elem_defn(header_anonymous_sequence_MVI_PsuData_unbounded, bound,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_sequence_MVI_PsuData_unbounded));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_sequence_type_identifier(seq_sdefn, "anonymous_sequence_MVI_PsuData_unbounded", type_ids_data))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_sequence_MVI_PsuData_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_data = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_data = 0x00000000;
            bool common_data_ec {false};
            CommonStructMember common_data {TypeObjectUtils::build_common_struct_member(member_id_data, member_flags_data, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_data, common_data_ec))};
            if (!common_data_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure data member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_data = "data";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_data;
            ann_custom_PsuDataSeq.reset();
            CompleteMemberDetail detail_data = TypeObjectUtils::build_complete_member_detail(name_data, member_ann_builtin_data, ann_custom_PsuDataSeq);
            CompleteStructMember member_data = TypeObjectUtils::build_complete_struct_member(common_data, detail_data);
            TypeObjectUtils::add_complete_struct_member(member_seq_PsuDataSeq, member_data);
        }
        CompleteStructType struct_type_PsuDataSeq = TypeObjectUtils::build_complete_struct_type(struct_flags_PsuDataSeq, header_PsuDataSeq, member_seq_PsuDataSeq);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_PsuDataSeq, type_name_PsuDataSeq.to_string(), type_ids_PsuDataSeq))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "MVI::PsuDataSeq already registered in TypeObjectRegistry for a different type.");
        }
    }
}
} // namespace MVI

